# Generated by Django 6.0.4 on 2026-04-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='views',
            field=models.FloatField(),
        ),
    ]
