# Generated by Django 6.0.4 on 2026-04-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0002_alter_stream_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
