# Generated by Django 6.0.4 on 2026-04-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='game_images')),
                ('rating', models.FloatField(default=5.0)),
                ('downloads', models.FloatField(default=0)),
            ],
        ),
    ]
